name: Build c8y2k

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.0

    - name: Build and Deploy
      run: |
        go build -o c8y2k
        ./c8y2k

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: c8y2k-artifact
        path: ./c8y2k
